### ISSUE TITLE
Any warning about using your widget?

### ISSUE THREAD

**Issue by nkosi23** [ConteZero/tw-updater-plasmoid#6]
Hello,

Being new to OpenSUSE, I had been using this widget successfully but I kept reading on the internet that upgrading Tumbleweed from the desktop environment is dangerous and could leave my system broken since it is a rolling release and a snapshot of everything is pushed every time. These warnings scared me so I stopped using the widget and now use the command line, which is impractical since it is not possible to use the computer when a Virtual Terminal is launched.

As the widget author, it would be interesting to know your take on the risks of using your widget.

Thanks!

**Comment by ConteZero** [comment]
My applet is basically a frontend to zypper, you can read more info on how it works here:
[https://www.contezero.com/linux/kde-plasma-software-updater-opensuse-tumbleweed](https://www.contezero.com/linux/kde-plasma-software-updater-opensuse-tumbleweed)

I have never had problems using it for my systems, but this does not mean that the update software is 100% reliable, whatever mode you use for the update the most important thing is that you always have backups available, this is the golden rule.
